language: node_js
node_js: '8'
cache:
  npm: true
script:
- npx tsc
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: HfvHX96qULCUzKne6sZ6DMt4u1IxgYf9oJCqDDqBsYG9FIwGd8WEgxUFxtNMG2bmxquMly8Qeysq//yK5R5bG3eQweslfFiD4kydmeFlmOvHt1bZQY9ArCCF9h8oEK8prJsnHWOsp4qTD+7FuTQHRTwrAP/I9hdq5LXq7L7Ay6kjuKB9dEdth/wSNosHHvQZh1q2trXDrN8reRFALnSjV+C0Ak0Vbzk+b1E0b06Qgc5htpGiJ+3BKQCyrI69PWDUFgZMSkLLB6qwMgseVlFDBcls6N5oxtQWBRQG1OSiYXxGp1W457PECf6YOP3FXIpuDCSW6VQ0/pWFU78bYboCAg7X6614LsQhUzdKxS0Jz66SCe6cJ1g8JR44wo64qaRSW2XfSCZgNaQw+IXyJJmcg2pxii9YahklP+gy0PHkhh4f94jR04ID1RHhD53uyTvpOFopiVxWOvACYgRwyfYzXW3ii3/nGg2Q5NwWXdiSP+QtMV0tswsmIYEB5KbRiQvZqqfPMk2/SbHmVAh08ttDAVZkArcs3DPx5MuTYMxNxNMZSTxHCAK/Z3zjkj5Ov4/Qagnr57zdUqac4yGGgwpyk4Txy2xMV+TM+MDs9zufFcPsAqKKl5jSM2FtHWcBrRNr9eShRDn0yodjrJb0gxboQA+wwH54v8teMekfCk4cSGk=
  - secure: BOkAmjD0GEE5VZU7pI6LHHwF+XyImD1iiYMgHAPp93CYNkxc+DkIafOyyulZY5kUbEnX0T73ZufrbFnNjy+8VqsiXNT5+xBLi6GdG8+CqjiwE28eX8r19Etju0/1j9OSNQEWXgv2gjQ8Ch7nLXXEtvPpE4aJ4YDP1YDUFGaJ+5zT2AxlrpTeH6RF2E3p4StJD78urnxgUjLvW+9LdZGM53Nob2D6XoeYDWBsOk2r9wYIuqJ3OCK1ASQ5Slbc0XGZDkFUFEO1dK5GMOv7s0hpHp018mkoNp6Sg+Pc9YK1AEHNsQW1JeiNkjnAHv8GF/bOcUFFtoo5G6H2F2Vi6wq+7eTloQxNBokAz8+lGDViop19UHpZIHCcyvF2J32fMGYn2afVNiDFlPq02cfZdWQDao7zgV83FQjHjPa+CmMq6AtGqO+F1kyUy551LpKtQzBcFy6T5oG52iOeZ94BVkrM6RfJyUKf5zciiIsH+ebGjt2UVrzrQROKOxknT3P0WBiK6gQFogiCNMutRcRcy/IjgXSiidwZomycH9I92Y/oaTgUXFsJhBblsEKkT1sLsTFlOFbiW6iiP90rP3pqq6sdGyxzeo72XVE+41W7PsGr5gn/pXQYD6kETQegn/lPuaxzNy35PkchTk9IuZVIc9TWwOSBOkSwNn/rYhROzFlI6Cc=
